### ISSUE TITLE
Consider a different name for this project

### ISSUE THREAD

**Issue by rdmark** [JensKSP/netatalk_classic#1]
These is an established project called [netatalk-classic](https://github.com/christopherkobayashi/netatalk-classic) with only the hyphen/underscore being the difference with the name of this project. You may want to proactively consider renaming your project! Totally up to you of course, but I could just imagine confusion down the road.

For the record: I'm not the owner of netatalk-classic, but I am a code contributor.

Regardless, I'm stoked to see more Netatalk related projects popping up! Thanks for working on this, and for submitting upstream patches.

**Comment by JensKSP** [comment]
Thanks for the hint. I was not aware of the naming conflict. I changed the name.
